import Foundation

public enum Country: String
{
	case worldwide = "random"
	case albania = "albania"
	case argentina = "argentina"
	case armenia =  "armenia"
	case australia =  "australia"
	case austria =  "austria"
	case azerbaijan =  "azerbaijan"
	case bangladesh =  "bangladesh"
	case belgium =  "belgium"
	case bosniaAndHerzegovina =  "bosnia and herzegovina"
	case brazil =  "brazil"
	case canada =  "canada"
	case china =  "china"
	case colombia =  "colombia"
	case denmark =  "denmark"
	case egypt =  "egypt"
	case england =  "england"
	case estonia =  "estonia"
	case finland =  "finland"
	case france =  "france"
	case georgia =  "georgia"
	case germany =  "germany"
	case greece = "greece"
	case hungary = "hungary"
	case india = "india"
	case iran = "iran"
	case israel = "israel"
	case italy = "italy"
	case japan = "japan"
	case korea = "korea"
	case mexico = "mexico"
	case morocco = "morocco"
	case netherlands = "netherlands"
	case newZealand = "newZealand"
	case nigeria = "nigeria"
	case norway = "norway"
	case pakistan = "pakistan"
	case poland = "poland"
	case portugal = "portugal"
	case romania = "romania"
	case russia = "russia"
	case slovakia = "slovakia"
	case slovenia = "slovenia"
	case spain = "spain"
	case sweden = "sweden"
	case switzerland = "switzerland"
	case turkey = "turkey" 
	case ukraine = "ukraine" 
	case unitedStates = "united states" 
	case vietnam = "vietnam" 
}